const YES_REPLIES: string[] = [
    "Anything you want.",
    "Immediately.",
    "Well done.",
    "Work, work.",
    "Be happy to.",
    "I can do that.",
    "Well done.",
    "Taz'dingo!",
    "Righty way!",
    "Dat be good choice, mon!",
    "A wise plan.",
    "It is destined.",
    "Excellent choice.",
    "I hear and obey.",
    "Of course.",
    "It is certain.",
    "Yes, chieftain.",
    "It be a pleasure!",
    "Whatever you say.",
    "Yes, master.",
    "I go unseen.",
    "I'll look into it...",
    "If it pleases you.",
    "I must obey...",
    "If that is your wish.",
    "As the shadow wills.",
    "As you order!",
    "For the Lich King!",
    "By your words!"
]